FROM golang:1.20 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o service-sentinel .
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/service-sentinel .
EXPOSE 80

CMD ["./service-sentinel"]
